name: fizika_adaptivno_vezbanje
description: Offline-first adaptive physics practice app.
publish_to: none
version: 0.1.1+2
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  http: ^1.5.0
  cryptography: ^2.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/content/manifest.json
    - assets/content/g1_fizika_1.3.0_PASS.json
    - assets/content/g3_magnetno_polje_3.0.0_PASS.json
