import 'models.dart';
class AdaptiveEngine {
 static const maxWindow=12,minAttempts=5,minUnique=3,cooldownAttempts=2;
 double _dw(Difficulty d)=>switch(d){Difficulty.basic=>1.0,Difficulty.intermediate=>1.25,Difficulty.advanced=>1.5};
 double _rw(int i)=>i<4?1.0:(i < 8 ? 0.85 : 0.70);
 LessonDiagnosis diagnose(List<Attempt> input){ final h=([...input]..sort((a,b)=>b.at.compareTo(a.at))).take(maxWindow).toList(); final unique=h.map((e)=>e.questionId).toSet().length; if (h.length < minAttempts || unique < minUnique) { return LessonDiagnosis(PracticeState.insufficientData, null, h.length, unique); } double sum=0,ok=0; for(var i=0;i<h.length;i++){final w=_dw(h[i].difficulty)*_rw(i);sum+=w;if(h[i].correct)ok+=w;} final s=100*ok/sum; final l5=h.take(5).toList(); final stable=h.length>=8&&unique>=4&&s>=75&&l5.where((e)=>e.correct).length>=4&&l5.map((e)=>e.questionId).toSet().length>=3; String? signal; final wrong=h.take(8).where((e)=>!e.correct&&e.errorCategory!=null); final cats=<String,List<Attempt>>{}; for(final x in wrong){cats.putIfAbsent(x.errorCategory!,()=>[]).add(x);} for(final e in cats.entries){if(e.value.length>=3&&e.value.map((x)=>x.questionId).toSet().length>=2){signal=e.key;break;}} final st=s<60?PracticeState.targetedPractice:s<75?PracticeState.consolidation:stable?PracticeState.stable:PracticeState.consolidation; return LessonDiagnosis(st,s,h.length,unique,errorSignal:signal); }
 List<Question> eligible(Iterable<Question> qs,int unlock,{bool adaptive=true,String? lessonId})=>qs.where((q)=>q.published&&q.scientificPass&&q.metadataComplete&&q.unlockOrder<=unlock&&(!adaptive||q.adaptiveEnabled)&&(lessonId==null||q.lessonId==lessonId)).toList();
 Difficulty preferredDifficulty(List<Attempt> input,Difficulty current){final h=([...input]..sort((a,b)=>b.at.compareTo(a.at))).take(3).toList(); if (h.length < 3) { return current; } if (h.every((e) => e.correct)) { return switch (current) { Difficulty.basic => Difficulty.intermediate, Difficulty.intermediate => Difficulty.advanced, Difficulty.advanced => Difficulty.advanced }; } if (h.where((e) => !e.correct).length >= 2) { return switch (current) { Difficulty.advanced => Difficulty.intermediate, Difficulty.intermediate => Difficulty.basic, Difficulty.basic => Difficulty.basic }; } return current;}
 List<Question> applyCooldown(List<Question> candidates,List<Attempt> recent){final blocked=recent.take(cooldownAttempts).map((e)=>e.questionId).toSet();final fresh=candidates.where((q)=>!blocked.contains(q.id)).toList();return fresh.isNotEmpty?fresh:candidates;}
}