import 'dart:math';

enum MasterLevel { basic, intermediate, advanced }

class TestQuestion {
  const TestQuestion({required this.id,required this.unlockOrder,required this.level,required this.nature,required this.representation,required this.subdomainId,required this.correctOptionId,required this.equivalenceGroup,required this.published,required this.scientificPass});
  final String id,nature,representation,subdomainId,correctOptionId,equivalenceGroup; final int unlockOrder; final MasterLevel level; final bool published,scientificPass;
}
class TestGenerationException implements Exception{TestGenerationException(this.reasons);final List<String> reasons;@override String toString()=>'Nedovoljan fond: ${reasons.join('; ')}';}

class MasterTestGenerator{
  MasterTestGenerator({Random? random}):_random=random??Random.secure();final Random _random;
  List<TestQuestion> _eligible(Iterable<TestQuestion> all,int unlock)=>all.where((q)=>q.published&&q.scientificPass&&q.unlockOrder<=unlock).toList();
  List<String> auditPool(Iterable<TestQuestion> all,int unlock){final q=_eligible(all,unlock),r=<String>[];int n(MasterLevel l)=>q.where((x)=>x.level==l).length;if(n(MasterLevel.basic)<8)r.add('manje od 8 osnovnih');if(n(MasterLevel.intermediate)<5)r.add('manje od 5 srednjih');if(n(MasterLevel.advanced)<3)r.add('manje od 3 napredna');if(q.where((x)=>x.nature=='theory').length<7)r.add('manje od 7 teorijskih');if(q.where((x)=>x.nature=='calculation').length<7)r.add('manje od 7 računskih');if(q.where((x)=>x.representation=='graph').length<2)r.add('manje od 2 grafička');if(q.where((x)=>x.representation=='table').isEmpty)r.add('nema tabelarnog');if(q.where((x)=>x.representation=='scheme').isEmpty)r.add('nema šematskog');return r;}
  List<TestQuestion> generate(Iterable<TestQuestion> all,int unlock){final r=auditPool(all,unlock);if(r.isNotEmpty)throw TestGenerationException(r);final pool=_eligible(all,unlock)..shuffle(_random);final chosen=<TestQuestion>[];for(final e in const {MasterLevel.basic:8,MasterLevel.intermediate:5,MasterLevel.advanced:3}.entries){final c=pool.where((q)=>q.level==e.key&&!chosen.any((x)=>x.id==q.id)).toList()..shuffle(_random);chosen.addAll(c.take(e.value));}if(chosen.length!=16)throw TestGenerationException(['nije moguće sastaviti 8+5+3']);_repairNature(chosen,pool);_repairVisuals(chosen,pool);_repairAnswers(chosen,pool);_repairCoverage(chosen,pool);return _antiPattern(chosen);}
  bool _validNature(List<TestQuestion> q){final t=q.where((x)=>x.nature=='theory').length,c=q.where((x)=>x.nature=='calculation').length;return t>=7&&t<=9&&c>=7&&c<=9;}
  void _repairNature(List<TestQuestion> q,List<TestQuestion> pool){for(var g=0;g<100&&!_validNature(q);g++){final t=q.where((x)=>x.nature=='theory').length;final need=t<7?'theory':'calculation',ex=need=='theory'?'calculation':'theory';final incoming=pool.where((x)=>x.nature==need&&!q.any((c)=>c.id==x.id)).toList()..shuffle(_random);var ok=false;for(final x in incoming){final i=q.indexWhere((c)=>c.nature==ex&&c.level==x.level);if(i>=0){q[i]=x;ok=true;break;}}if(!ok)break;}if(!_validNature(q))throw TestGenerationException(['nije moguće postići dozvoljeni odnos teorija/račun 45:55–55:45']);}
  void _repairVisuals(List<TestQuestion> q,List<TestQuestion> pool){for(final e in const {'graph':2,'table':1,'scheme':1}.entries){while(q.where((x)=>x.representation==e.key).length<e.value){final inc=pool.where((x)=>x.representation==e.key&&!q.any((c)=>c.id==x.id)).toList()..shuffle(_random);if(inc.isEmpty)throw TestGenerationException(['nedovoljan fond za ${e.key}']);final x=inc.first;final i=q.indexWhere((c)=>c.level==x.level&&c.nature==x.nature&&!const {'graph','table','scheme'}.contains(c.representation));if(i<0)throw TestGenerationException(['vizuelni zahtev se ne može uklopiti']);q[i]=x;}}}
  void _repairAnswers(List<TestQuestion> q,List<TestQuestion> pool){int cnt(String a)=>q.where((x)=>x.correctOptionId==a).length;for(var g=0;g<100;g++){final over=['A','B','V','G'].where((a)=>cnt(a)>5).toList(),under=['A','B','V','G'].where((a)=>cnt(a)<3).toList();if(over.isEmpty&&under.isEmpty)return;if(under.isEmpty)return;final want=under.first;final inc=pool.where((x)=>x.correctOptionId==want&&!q.any((c)=>c.id==x.id)).toList()..shuffle(_random);var changed=false;for(final x in inc){final i=q.indexWhere((c)=>over.contains(c.correctOptionId)&&c.level==x.level&&c.nature==x.nature&&c.representation==x.representation);if(i>=0){q[i]=x;changed=true;break;}}if(!changed)break;}if(['A','B','V','G'].any((a)=>cnt(a)<3||cnt(a)>5))throw TestGenerationException(['nije moguće postići približno ravnomeran A/B/V/G bez kršenja ostalih uslova']);}
  void _repairCoverage(List<TestQuestion> q,List<TestQuestion> pool){final domains=pool.map((x)=>x.subdomainId).toSet();for(final d in domains){if(q.any((x)=>x.subdomainId==d))continue;final inc=pool.where((x)=>x.subdomainId==d&&!q.any((c)=>c.id==x.id)).toList()..shuffle(_random);var changed=false;for(final x in inc){final counts=<String,int>{};for(final z in q){counts[z.subdomainId]=(counts[z.subdomainId]??0)+1;}final i=q.indexWhere((c)=>(counts[c.subdomainId]??0)>1&&c.level==x.level&&c.nature==x.nature&&c.representation==x.representation&&c.correctOptionId==x.correctOptionId);if(i>=0){q[i]=x;changed=true;break;}}if(!changed)throw TestGenerationException(['nije moguće reprezentativno pokriti sve izabrane oblasti']);}}
  List<TestQuestion> _antiPattern(List<TestQuestion> src){final rem=[...src]..shuffle(_random),out=<TestQuestion>[];while(rem.isNotEmpty){final valid=rem.where((q)=>!(out.length>=2&&out[out.length-1].subdomainId==q.subdomainId&&out[out.length-2].subdomainId==q.subdomainId)&&!(out.length>=2&&out[out.length-1].correctOptionId==q.correctOptionId&&out[out.length-2].correctOptionId==q.correctOptionId)&&!(out.isNotEmpty&&out.last.equivalenceGroup.isNotEmpty&&out.last.equivalenceGroup==q.equivalenceGroup)).toList();final c=valid.isNotEmpty?valid:rem,p=c[_random.nextInt(c.length)];out.add(p);rem.remove(p);}return out;}
}
